CREATE TABLE IF NOT EXISTS projects(
  id_project INTEGER PRIMARY KEY generated BY DEFAULT as IDENTITY,
  nombre_project text NOT NULL CHECK (nombre_project<>''),
  prioridad_project INTEGER NOT NULL,
  descripcion_project TEXT,
  fechaentrega_project DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
  id_task INTEGER PRIMARY KEY generated BY DEFAULT AS IDENTITY,
  nombre_task TEXT NOT NULL CHECK (nombre_task<>''),
  estado_task BOOLEAN,
  id_project INTEGER REFERENCES projects(id_project)
);

INSERT INTO projects(nombre_project,prioridad_project,descripcion_project,fechaentrega_project)
VALUES('Make a Web App',1,'Usando Javascript','2019-05-17');
INSERT INTO projects(nombre_project,prioridad_project,descripcion_project,fechaentrega_project)
VALUES('Make a App',1,'Usando Dart','2019-04-12');
INSERT INTO projects(nombre_project,prioridad_project,descripcion_project,fechaentrega_project)
VALUES('Make a Destop App',1,'Usando C++','2019-05-13');


--insertar tasks

INSERT INTO task(nombre_task,estado_task,id_project)
VALUES('donwload Vuejs',false,1);
INSERT INTO task(nombre_task,estado,id_project)
VALUES('Create UI Web',false,1);
INSERT INTO task(nombre_task,estado,id_project)
VALUES('donwload Flutter',false,2);
INSERT INTO task(nombre_task,estado,id_project)
VALUES('Design UI',false,2);